# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/hello.proto',
  package='hello',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11proto/hello.proto\x12\x05hello\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2K\n\x08Greeting\x12?\n\x0eGreetingServer\x12\x0b.hello.Name\x1a\x0e.hello.Message\"\x10\x82\xd3\xe4\x93\x02\n\"\x05/name:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='hello.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hello.Name.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=78,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='hello.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello.Message.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Name'] = _NAME
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
  'DESCRIPTOR' : _NAME,
  '__module__' : 'proto.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.Name)
  })
_sym_db.RegisterMessage(Name)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'proto.hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.Message)
  })
_sym_db.RegisterMessage(Message)



_GREETING = _descriptor.ServiceDescriptor(
  name='Greeting',
  full_name='hello.Greeting',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=108,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='GreetingServer',
    full_name='hello.Greeting.GreetingServer',
    index=0,
    containing_service=None,
    input_type=_NAME,
    output_type=_MESSAGE,
    serialized_options=_b('\202\323\344\223\002\n\"\005/name:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETING)

DESCRIPTOR.services_by_name['Greeting'] = _GREETING

# @@protoc_insertion_point(module_scope)
